name: Build Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    needs: release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: tmp
      
    - name: Build and Clean Up
      run: |
        make
        find . -mindepth 1 -not -path './include' -not -path './lib' -not -path './bin' -exec rm -rf {} +
      working-directory: tmp

    - name: Upload Library
      uses: actions/upload-artifact@v4
      with:
        name: ZLib-Linux
        path: ./tmp

    - name: Tar it All Up
      run: tar -czf ./ZLib.tar.gz ./tmp

    - name: Upload Package to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./ZLib.tar.gz
        asset_name: ZLib-Linux.test-${{ github.sha }}.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
    - uses: actions/checkout@v4
      with:
        path: tmp
      
    - name: Tar it All Up
      run: tar -czf ./ZLib.tar.gz ./tmp

    - name: Upload Library
      uses: actions/upload-artifact@v4
      with:
        name: ZLib-Linux
        path: ./ZLib.tar.gz

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: test-${{ github.sha }}
        release_name: ZLib Test Release ${{ github.sha }}
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Package to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ZLib.tar.gz
        asset_name: ZLib-Source.test-${{ github.sha }}.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}