name: Build Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: mkdir lib
    
    - name: build
      run: make

    - name: Upload Library
      uses: actions/upload-artifact@v4
      with:
        name: ZLib-linux
        path: ./lib/ZLib.so
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - run: mkdir b
    - run: cd b
    
    - uses: actions/checkout@v4
    
    - run: mkdir ./lib
    
    - name: Download Built Lib
      uses: actions/download-artifact@v4
      with:
        name: ZLib-linux
        path: ./lib

    - name: Remove unneeded files and directories
      run: find . -mindepth 1 -not -path './include' -not -path './lib' -exec rm -rf {} +
      
    - name: Archive Library
      run: tar -czf ./prebuilt-linux.tar.gz ../

    - run: cd ..
    - run: mkdir s
    - run: cd s
    
    - uses: actions/checkout@v4

    - name: Archive Source
      run: tar -czf ./source.tar.gz ../

    - run: cd ..
      
    - name: Upload Package
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.__RAT__ }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @./prebuilt-linux.tar.gz \
          "https://uploads.github.com/repos/${{ github.repository }}/packages/${{ github.sha }}/assets"
        
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.__RAT__ }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @./source.tar.gz \
          "https://uploads.github.com/repos/${{ github.repository }}/packages/${{ github.sha }}/assets"

      env:
        GITHUB_TOKEN: ${{ secrets.__RAT__ }}
