name: Build Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: mkdir tmp

    - uses: actions/checkout@v4
      with:
        path: tmp
      
    - name: Build and Clean Up
      run: |
        make
        find . -mindepth 1 -not -path './include' -not -path './lib' -not -path './bin' -exec rm -rf {} +
      working-directory: tmp

    - name: Tar it All Up
      run: tar -czf ./ZLib.tar.gz ./tmp

    - name: Upload Library
      uses: actions/upload-artifact@v4
      with:
        name: ZLib-Linux
        path: ./ZLib.tar.gz

    - name: Upload Package
      run: |
        curl -X POST \
          -H "Authorization: Bearer $TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @./ZLib.tar.gz \
          "https://uploads.github.com/repos/${{ github.repository }}/packages/test${{ github.sha }}/assets?name=ZLib-Linux.test-${{ github.sha }}.tar.gz"
          
      env:
        TOKEN: ${{ secrets.__RAT__ }}

  release:
    runs-on: ubuntu-latest

    steps:
    - run: mkdir tmp

    - uses: actions/checkout@v4
      with:
        path: tmp
      
    - name: Tar it All Up
      run: tar -czf ./ZLib.tar.gz ./tmp

    - name: Upload Library
      uses: actions/upload-artifact@v4
      with:
        name: ZLib-Linux
        path: ./ZLib.tar.gz

    - name: Upload Package
      run: |
        curl -X POST \
          -H "Authorization: Bearer $TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @./ZLib.tar.gz \
          "https://uploads.github.com/repos/${{ github.repository }}/packages/test${{ github.sha }}/assets?name=ZLib-Source.test-${{ github.sha }}.tar.gz"
          
      env:
        TOKEN: ${{ secrets.__RAT__ }}
